title: pyralab.org
author:
  name: han shu
  email: tom.shuhan@gmail.com
# description: > # this means to ignore newlines until "show_excerpts:"
#   A blog website for han shu.
#   This blog website is using the theme jekyll/minima.
  
site_name: pyralab.org

collections:
  articles:
    output: true
    permalink: /:path

show_excerpts: false # set to true to show excerpts on the homepage

# Minima date format
# refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%b %-d, %Y"

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.md

# Build settings
theme: minima

plugins:
 - jekyll-feed
 - jekyll-seo-tag

# markdown: kramdown

# kramdown:
#   math_engine: katex
