title: pyralab.org
author:
  name: pyralab.org
  email: feedback2pyralab@gmail.com
  
site_name: pyralab.org

collections:
  articles:
    output: true
    permalink: /:path

show_excerpts: false 

minima:
  date_format: "%b %-d, %Y"

theme: minima

plugins:
 - jekyll-feed
 - jekyll-seo-tag
