title: pyralab.org
author:
  name: pyralab.org
  email: feedback2pyralab@gmail.com
  
site_name: pyralab.org

icon_link: https://cdn.jsdelivr.net/gh/R1szW7xqoVdA/Vu-jewdLEw--f-_-/icon/icon.ico
svg_link: https://cdn.jsdelivr.net/gh/R1szW7xqoVdA/Vu-jewdLEw--f-_-/icon/icon.svg

collections:
  articles:
    output: true
    permalink: /:path

show_excerpts: false 

minima:
  date_format: "%b %-d, %Y"

theme: minima

plugins:
 - jekyll-feed
 - jekyll-seo-tag
